
package webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Registration", targetNamespace = "http://webservice.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Registration {


    /**
     * 
     * @param arg0
     * @return
     *     returns webclient.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://webservice.auction/", className = "webclient.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://webservice.auction/", className = "webclient.GetUserResponse")
    @Action(input = "http://webservice.auction/Registration/getUserRequest", output = "http://webservice.auction/Registration/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webclient.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://webservice.auction/", className = "webclient.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://webservice.auction/", className = "webclient.RegisterUserResponse")
    @Action(input = "http://webservice.auction/Registration/registerUserRequest", output = "http://webservice.auction/Registration/registerUserResponse")
    public User registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clean", targetNamespace = "http://webservice.auction/", className = "webclient.Clean")
    @ResponseWrapper(localName = "cleanResponse", targetNamespace = "http://webservice.auction/", className = "webclient.CleanResponse")
    @Action(input = "http://webservice.auction/Registration/cleanRequest", output = "http://webservice.auction/Registration/cleanResponse")
    public void clean();

}
